version: '3'
services:
  container_a:
    build: 
      context: ./a
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
  container_b:
    build: 
      context: ./b
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
